"""Generated host secrets and the single secret-file reader.

Secrets are files under ``/etc/gideon/secrets``.  Generated values are written
only when absent by apply; ``secrets rotate`` rewrites the ``rewrite`` and
``remint`` classes.  The registry is release policy, not site configuration.
"""

import hashlib
import re
import secrets as token_secrets
import subprocess
from collections.abc import Mapping
from dataclasses import dataclass, field
from pathlib import Path
from typing import Final, Literal

from gideon.host.sysio import Host

SecretKind = Literal["password", "minted"]
"""Secret categories; ``password`` is generated by the secrets stage."""
RotationClass = Literal["rewrite", "remint", "role", "account", "seeded"]
"""How a secret's value is held beyond its file, if anywhere."""
# A file rotation is safe only when the file alone holds the value; a second
# home must be changed through that consumer's own route.
SECRETS_DIR: Final = Path("/etc/gideon/secrets")
SERVICE_GROUP: Final = "gideon"
SERVICE_GROUP_PROBLEM: Final = f"the {SERVICE_GROUP} service group is missing or invalid"
_SERVICE_GROUP_FIX: Final = (
    "Run sudo python3 -m gideon host provision --only service-user, then retry."
)


@dataclass(frozen=True, slots=True)
class GeneratedSecret:
    """One release-managed secret and the component that consumes it."""

    name: str
    kind: SecretKind
    print_once: bool
    consumer: str
    rotation: RotationClass


@dataclass(frozen=True, slots=True)
class SuppliedSecret:
    """An office-supplied secret and the path for replacing its value."""

    name: str
    replaced_by: str


@dataclass(frozen=True, slots=True)
class RotateResult:
    """The content-free result of rewriting one generated secret file."""

    written: bool = False
    problem: str | None = None
    fix: str = ""

    @property
    def ok(self) -> bool:
        return self.problem is None


# The consumer is kept beside each entry so the release's secret inventory is
# reviewable without searching the renderer or Compose templates.
SECRET_REGISTRY: Final[tuple[GeneratedSecret, ...]] = (
    GeneratedSecret("postgres_superuser_password", "password", False, "postgres", "role"),
    GeneratedSecret("postgres_openwebui_password", "password", False, "Open WebUI database role", "role"),
    GeneratedSecret("postgres_gideon_password", "password", False, "GIDEON database role", "role"),
    GeneratedSecret(
        "postgres_gideon_audit_password",
        "password",
        False,
        "audit writer database role and frontend guardrail trip writer",
        "role",
    ),
    GeneratedSecret("webui_secret_key", "password", False, "Open WebUI session signing", "rewrite"),
    GeneratedSecret("gideon_admin_password", "password", True, "break-glass Open WebUI administrator", "account"),
    GeneratedSecret("gideon_eval_password", "password", False, "GIDEON evaluation identity", "account"),
    GeneratedSecret("grafana_admin_password", "password", True, "break-glass Grafana administrator", "seeded"),
    GeneratedSecret("postgres_gideon_ro_metrics_password", "password", False, "metrics reader database role", "role"),
    GeneratedSecret("engine_api_key", "password", False, "the engine's API key (gideon-generator)", "rewrite"),
    GeneratedSecret("searxng_secret_key", "password", False, "SearXNG's signing key", "rewrite"),
    GeneratedSecret("gideon_admin_api_key", "minted", False, "apply and reconcile", "remint"),
    GeneratedSecret("gideon_eval_api_key", "minted", False, "evaluation identity", "remint"),
)
GENERATED_NAMES: Final[frozenset[str]] = frozenset(
    secret.name for secret in SECRET_REGISTRY
)
ROTATABLE_NAMES: Final[frozenset[str]] = frozenset(
    secret.name
    for secret in SECRET_REGISTRY
    if secret.rotation in {"rewrite", "remint"}
)

_APPLY_COMMAND: Final = "sudo python3 -m gideon apply"
# Grafana mounts the two below as Compose file secrets, and apply's recreate
# rule judges rendered files only, so its recreate after a replacement is by
# hand (the gap slice-1 ticket 24's triage recorded).
_GRAFANA_RECREATE: Final = (
    "sudo docker compose -f /etc/gideon/rendered/compose.yaml "
    "up -d --no-deps --force-recreate grafana"
)


def _grafana_mounted_replacement(name: str) -> str:
    return (
        f"Replace {SECRETS_DIR / name}, run {_APPLY_COMMAND}, then force-recreate "
        f"Grafana, which mounts it and which apply's recreate rule does not see: "
        f"{_GRAFANA_RECREATE}."
    )


# The office's replacement path per supplied secret (§1.7's four), the fix the
# rotation command prints for each; every path is a command sequence (§1.5).
SUPPLIED_REGISTRY: Final[tuple[SuppliedSecret, ...]] = (
    SuppliedSecret(
        "tls_key",
        "Replace the certificate and key at their fixed homes (§1.6), then run "
        "sudo python3 -m gideon tls reload.",
    ),
    SuppliedSecret("ldap_bind_password", _grafana_mounted_replacement("ldap_bind_password")),
    SuppliedSecret("smtp_password", _grafana_mounted_replacement("smtp_password")),
    SuppliedSecret(
        "proxy_auth",
        f"Replace {SECRETS_DIR / 'proxy_auth'}, then run {_APPLY_COMMAND} (both env "
        "files re-render and their owners are recreated through the recreate rule).",
    ),
)
SUPPLIED_NAMES: Final[frozenset[str]] = frozenset(
    secret.name for secret in SUPPLIED_REGISTRY
)


def registry_entry(name: str) -> GeneratedSecret | None:
    """Return the generated registry entry named *name*, if any."""

    return next((secret for secret in SECRET_REGISTRY if secret.name == name), None)


def is_generated(name: str) -> bool:
    """True when *name* is a release-generated secret rather than a supplied one."""

    return name in GENERATED_NAMES


@dataclass(frozen=True, slots=True)
class SecretReadResult:
    """The contents of a secret file, or a fix-bearing read refusal.

    ``missing`` distinguishes an absent file from an unreadable one so a caller
    can name the command that generates it instead of a repair.
    """

    value: str | None = None
    problem: str | None = None
    fix: str = ""
    missing: bool = False

    @property
    def ok(self) -> bool:
        return self.problem is None


@dataclass(frozen=True, slots=True)
class EnsureResult:
    """The generated secrets and any print-once values from one ensure pass."""

    created: tuple[str, ...] = ()
    printed: Mapping[str, str] = field(default_factory=dict)
    problem: str | None = None
    fix: str = ""

    @property
    def ok(self) -> bool:
        return self.problem is None


def secret_path(name: str) -> Path:
    """The file a named secret lives in, resolved when called (never at import)."""

    return SECRETS_DIR / name


def read_secret(host: Host, name: str) -> SecretReadResult:
    """Read a named secret below ``/etc/gideon/secrets`` through the seam."""

    path = secret_path(name)
    if path.name != name or not name:
        return SecretReadResult(
            problem=f"Invalid secret file name: {name!r}.",
            fix="Use a secret file name under /etc/gideon/secrets.",
        )
    try:
        value = host.read_text(path).rstrip("\r\n")
    except FileNotFoundError:
        return SecretReadResult(
            problem=f"Secret file is missing: {path}.",
            fix=f"Place the secret in {path}, then retry.",
            missing=True,
        )
    except UnicodeDecodeError:
        return SecretReadResult(
            problem=f"Secret file is not valid UTF-8: {path}.",
            fix="Correct the secret file, then retry.",
        )
    except OSError as exc:
        return SecretReadResult(
            problem=f"Secret file is unreadable: {path} ({exc}).",
            fix="Correct the secret file, then retry.",
        )
    return SecretReadResult(value=value)


def service_group_gid(host: Host) -> int | None:
    """The gid of the ``gideon`` service group through the seam; ``None`` when absent or malformed.

    The one place the group is resolved: secrets are written ``root:gideon``,
    the secrets-dirs step converges them to it, and render puts the gid in the
    unprivileged services' ``group_add``.
    """

    result = host.run(["getent", "group", SERVICE_GROUP])
    if result.returncode != 0:
        return None
    for line in result.stdout.splitlines():
        fields = line.split(":")
        if len(fields) >= 3 and fields[0] == SERVICE_GROUP:
            try:
                return int(fields[2])
            except ValueError:
                return None
    return None


def _write_secret(
    host: Host, name: str, value: str, service_gid: int
) -> tuple[str | None, bool]:
    path = secret_path(name)
    try:
        host.write_text(path, value + "\n", mode=0o440)
    except OSError as exc:
        return f"unable to write {path}: {exc}.", False
    try:
        host.chown(path, 0, service_gid)
    except OSError as exc:
        return f"{path} was written but unowned: chown to root:{SERVICE_GROUP} failed: {exc}.", True
    return None, True


def write_secret(host: Host, name: str, value: str) -> str | None:
    """Write a secret as ``root:gideon`` at mode 0440 through the seam."""

    path = secret_path(name)
    if path.name != name or not name:
        return f"Invalid secret file name: {name!r}."
    service_gid = service_group_gid(host)
    if service_gid is None:
        return f"{SERVICE_GROUP_PROBLEM}."
    problem, _ = _write_secret(host, name, value, service_gid)
    return problem


def rotate_generated(host: Host, name: str) -> RotateResult:
    """Rewrite a ``rewrite`` secret in place without exposing its new value."""

    entry = registry_entry(name)
    if entry is None:
        return RotateResult(
            problem=f"Secret is not a generated registry entry: {name}.",
            fix="Choose a generated secret with rotation class rewrite.",
        )
    if entry.rotation != "rewrite":
        return RotateResult(
            problem=f"Secret {name} has rotation class {entry.rotation}, not rewrite.",
            fix="Choose a generated secret with rotation class rewrite.",
        )
    service_gid = service_group_gid(host)
    if service_gid is None:
        return RotateResult(problem=f"{SERVICE_GROUP_PROBLEM}.", fix=_SERVICE_GROUP_FIX)
    problem, written = _write_secret(
        host, name, token_secrets.token_urlsafe(32), service_gid
    )
    if problem is not None:
        # A value that reached the path is a rotation no consumer has yet:
        # apply converges its carriers, and a fresh rotation reaches the rest.
        fix = (
            f"Run sudo chown root:{SERVICE_GROUP} {secret_path(name)}, then {_APPLY_COMMAND}, "
            f"then sudo python3 -m gideon secrets rotate {name}."
            if written
            else f"Correct ownership and mode for {SECRETS_DIR}, then retry."
        )
        return RotateResult(written=written, problem=problem, fix=fix)
    return RotateResult(written=written)


def ensure_generated(host: Host) -> EnsureResult:
    """Create absent password-kind registry entries with mode ``0440``."""

    if host.geteuid() != 0:
        return EnsureResult(
            problem="generated secrets require root privileges.",
            fix="Run `sudo python3 -m gideon apply` as root, then retry.",
        )
    if not host.exists(SECRETS_DIR):
        return EnsureResult(
            problem=f"Secrets directory is missing: {SECRETS_DIR}.",
            fix="Run `sudo python3 -m gideon host provision --only secrets-dirs`, then retry.",
        )

    service_gid = service_group_gid(host)
    if service_gid is None:
        return EnsureResult(problem=f"{SERVICE_GROUP_PROBLEM}.", fix=_SERVICE_GROUP_FIX)

    created: list[str] = []
    printed: dict[str, str] = {}
    for secret in SECRET_REGISTRY:
        if secret.kind != "password":
            continue
        if host.exists(secret_path(secret.name)):
            continue
        value = token_secrets.token_urlsafe(32)
        problem, _ = _write_secret(host, secret.name, value, service_gid)
        if problem is not None:
            return EnsureResult(
                tuple(created),
                printed,
                problem=f"Unable to create generated secret: {problem}",
                fix="Correct ownership and mode for /etc/gideon/secrets, then retry.",
            )
        created.append(secret.name)
        if secret.print_once:
            printed[secret.name] = value
    return EnsureResult(tuple(created), printed)


_FINGERPRINT_KEY: Final = "webui_secret_key"
_SHA256_LINE: Final = re.compile(r"^([0-9a-fA-F]{64})\s+(.+)$")


def secrets_fingerprint(digests: Mapping[str, str]) -> str | None:
    """A fingerprint of the secret set that reveals nothing about any secret.

    It is a hash keyed by the digest of the generated, high-entropy
    ``webui_secret_key``: without that digest no guess at a human-chosen
    secret can be tested against it, so it may sit in a plaintext manifest.
    ``None`` when the key is absent (no secret set to fingerprint).
    """

    key = digests.get(_FINGERPRINT_KEY)
    if key is None:
        return None
    body = "\n".join(
        f"{name}:{digest.lower()}"
        for name, digest in sorted(digests.items())
        if name != _FINGERPRINT_KEY
    )
    return hashlib.sha256(f"{key.lower()}\n{body}".encode()).hexdigest()


def fingerprint(host: Host) -> str | None:
    """The live secret directory's fingerprint through the seam, or None."""

    try:
        result = host.run(
            ["find", str(SECRETS_DIR), "-type", "f", "-exec", "sha256sum", "{}", "+"]
        )
    except (OSError, subprocess.SubprocessError):
        return None
    if result.returncode != 0:
        return None
    digests: dict[str, str] = {}
    prefix = f"{SECRETS_DIR}/"
    for line in result.stdout.splitlines():
        match = _SHA256_LINE.match(line)
        if match is None:
            continue
        digests[match.group(2).removeprefix(prefix)] = match.group(1)
    return secrets_fingerprint(digests)
